backend:
  name: git-gateway
  branch: main
media_folder: "dist/assets/images"
public_folder: "/assets/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    slug: {{year}}-{{month}}-{{day}}-{{slug}}
    fields:
      - {label: "Tags", name: "tags", widget: "list", default: ["posts"]}
      - {label: "Content", minimal: true, name: "body", widget: "markdown"}
